if(NOT CACHE_ROOT_DIR)
set(CACHE_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/cache_system)
endif()
if(EXISTS "${CACHE_ROOT_DIR}/CMakeLists.txt")
add_subdirectory(${CACHE_ROOT_DIR} cache_system)
set(_CACHE_LIBRARIES cache_${_LIB_SUFFIX})
set(_CACHE_INCLUDE_DIR "${CACHE_ROOT_DIR}/include" "${CACHE_ROOT_DIR}/proto")
else()
message(WARNING "CACHE_ROOT_DIR not have CMakeLists.txt")
endif()