if(NOT NETLINK_ROOT_DIR)
set(NETLINK_ROOT_DIR ${CMAKE_CURRENT_SOURCE_DIR}/thirdparty/netLink)
endif()
if(EXISTS "${NETLINK_ROOT_DIR}/CMakeLists.txt")
add_subdirectory(${NETLINK_ROOT_DIR} netLink)
set(_NETLINK_LIBRARIES ${_LIB_SUFFIX})
set(_NETLINK_INCLUDE_DIR "${NETLINK_ROOT_DIR}/include")
else()
message(WARNING "NETLINK_ROOT_DIR not have CMakeLists.txt")
endif()